networks:
  appnetwork:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-inilabs
    restart: always
    ports:
      - "${PORT_NGINX:-80}:80"
      - "${PORT_SSL:-443}:443"  # Habilita el puerto 443 para SSL
    volumes:
      - ./web:/var/www/html   # Asegúrate de que este path apunte a tu proyecto PHP
      - ./docker/nginx/${NGINX_CONF_FILE:-default.conf}:/etc/nginx/conf.d/default.conf
      # - ./docker/nginx/logs:/var/log/nginx
      # - ./docker/nginx/certs:/etc/nginx/certs  # Monta la carpeta de certificados
      # - /etc/letsencrypt:/etc/letsencrypt  # Monta la carpeta de certificados de Let's Encrypt
    depends_on:
      - php
    networks:
      - appnetwork

  mysql:
    image: mysql:5.7.32
    container_name: mysql-inilabs
    restart: always
    tty: true
    ports:
      - "${PORT_MYSQL:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=s3cUr3P@ssw0rd!  # Contraseña segura
      - MYSQL_USER=secureuser
      - MYSQL_PASSWORD=s3cUr3P@ssw0rd!  # Contraseña segura
      - MYSQL_DATABASE=db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/inilabs.sql:/docker-entrypoint-initdb.d/inilabs.sql
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  php:
    build:
      context: ./web  # Cambia esta ruta si es necesario
      dockerfile: Dockerfile
    container_name: php-inilabs
    restart: always
    volumes:
      - ./web:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/html/.env
    ports:
      - "9000:9000"  # Esto es para FPM, Nginx lo usará internamente
    networks:
      - appnetwork
    depends_on:
      mysql:
        condition: service_healthy

  nextjs:
    build:
      context: ./duolingo-clone  # Cambia esta ruta si es necesario
      dockerfile: DockerfileNext  # Ruta al Dockerfile de Next.js
    container_name: duolingo-clone-container
    restart: always
    ports:
      - "3000:3000"  # Exponer Next.js en el puerto 3000
    networks:
      - appnetwork

volumes:
  mysql_data:
